version: '3'
services:

  react:
    build: ./react
    container_name: kanban-react
    environment:
      - API_HOST=localhost
      - API_PORT=7711
    ports:
     - "7710:8080"
    networks:
      - kanban-docker-network

  ruby:
    build: ./ruby
    container_name: kanban-ruby
    environment:
    - DATABASE_URL=postgres://postgres:kanban@db/kanban
    ports:
     - "7711:3000"
    networks:
      - kanban-docker-network
    links:
      - db
    depends_on:
      - db

  db:
    image: "postgres:10-alpine"
    container_name: kanban-db
    volumes:
      - db:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - DEBUG=false
      - POSTGRES_PASSWORD=kanban
    networks:
      - kanban-docker-network

networks:
  kanban-docker-network:
    driver: bridge
volumes:
  db: